package com.maitena.diact1_1;

import javax.swing.JFrame;

public class Principal extends JFrame {
    private final Alumno[] listaAlumnos = new Alumno[5];
    private int pos=0;
    private Alumno alumnoMasJoven=null;
    private int alumnosMayores;
    private int alumnosMenores;
    private boolean hayVacantes=true;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public Principal() {
        initComponents();
        if(alumnoMasJoven==null){
            txtAlumnoMasJoven.setText("Todavía no hay alumnos registrados");
        }else{
            txtAlumnoMasJoven.setText("Alumno más joven: " + alumnoMasJoven.getNombre() + " " + alumnoMasJoven.getApellidos() + " (" + alumnoMasJoven.getEdad() + " años)");

        }
        txtAlumnosMayoresEdad.setText(String.valueOf(alumnosMayores));
        txtAlumnosMenoresEdad.setText(String.valueOf(alumnosMenores));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblAlumnoMasJoven = new javax.swing.JLabel();
        txtAlumnoMasJoven = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblAlumnosMayoresEdad = new javax.swing.JLabel();
        txtAlumnosMayoresEdad = new javax.swing.JLabel();
        lblAlumnosMenoresEdad = new javax.swing.JLabel();
        txtAlumnosMenoresEdad = new javax.swing.JLabel();
        txtNoHayVacantes = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setText("Formulario de inscripción");

        lblNombre.setText("Nombre:");

        lblApellidos.setText("Apellidos:");

        lblEmail.setText("Email:");

        lblEdad.setText("Edad:");

        lblTelefono.setText("Teléfono:");

        lblAlumnoMasJoven.setText("Alumno más joven:");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblAlumnosMayoresEdad.setText("Alumnos mayores de edad:");

        lblAlumnosMenoresEdad.setText("Alumnos menores de edad:");

        txtNoHayVacantes.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlumnoMasJoven, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(txtAlumnoMasJoven, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAlumnosMenoresEdad)
                                    .addComponent(lblAlumnosMayoresEdad))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlumnosMayoresEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlumnosMenoresEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNoHayVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnEnviar)))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNoHayVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAlumnoMasJoven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAlumnoMasJoven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlumnosMayoresEdad)
                    .addComponent(txtAlumnosMayoresEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlumnosMenoresEdad)
                    .addComponent(txtAlumnosMenoresEdad))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblApellidos.getAccessibleContext().setAccessibleName("Apellidos");
        lblTelefono.getAccessibleContext().setAccessibleName("telefono");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        /* Recogemos los datos de formulario, comprobamos que no hay campos vacios
        y los pasamos para crear un nuevo alumno. Hay que parsear la edad porque llega como String */
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String email = txtEmail.getText();
        String edad = txtEdad.getText();
        String telefono = txtTelefono.getText();
        //Comprobamos que no hay campos vacios y registramos al alumno
        if (!nombre.isEmpty() && !apellidos.isEmpty() && !email.isEmpty() && !edad.isEmpty() && !telefono.isEmpty()) {
            //Comprobamos si hay vacantes
            if(hayVacantes){
                //Comprobamos que la edad sea un numero
                int edadInt;
                try {
                    edadInt = Integer.parseInt(edad); 
                } catch (NumberFormatException e) {
                    JDialogRegistroErroneo mensajeCampoVacio = new JDialogRegistroErroneo(this,true);
                    mensajeCampoVacio.setVisible(true);
                    return;
                }
                
                //Guardamos el alumno
                Alumno alumno = new Alumno(txtNombre.getText(),txtApellidos.getText(),txtEmail.getText(),edadInt, txtTelefono.getText());
        
                //Agregamos el alumno a la lista y movemos una posicion en el array. Si no hay más vacantes lo ponemos en false
                listaAlumnos[pos] = alumno;
                pos++;
                if(pos==5){
                    hayVacantes= false;
                }
                
                //Abrimos una ventana de dialogo para confirma que se ha regritrado con exito
                JDialogRegistroCorrecto mensaje = new JDialogRegistroCorrecto(this,true);
                mensaje.setVisible(true);
                
                //Actualizamos el alumno más joven
                if (alumnoMasJoven == null) {
                    alumnoMasJoven = alumno; 
                } else {
                    for (Alumno alumnoJ : listaAlumnos) {

                        if (alumnoJ != null && alumnoJ.getEdad() < alumnoMasJoven.getEdad()) {
                            alumnoMasJoven = alumnoJ;
                        }
                    }
                }
                
               //Actualizamos número de mayores y menores
                if(edadInt >=18){
                    alumnosMayores++;
                }else{
                    alumnosMenores++;
                }    
            }else{
                JDialogErrorNoHayVacantes mensajeNoHayVacantes = new JDialogErrorNoHayVacantes(this,true);
                mensajeNoHayVacantes.setVisible(true);  
            }
            
        }else{
            JDialogRegistroErroneo mensajeCampoVacio = new JDialogRegistroErroneo(this,true);
            mensajeCampoVacio.setVisible(true); 
        }  

        //Vaciamos los campos del formulario
        txtNombre.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");

        //Actualizamos la informacion
        txtAlumnoMasJoven.setText("Alumno más joven: " + alumnoMasJoven.getNombre() + " " + alumnoMasJoven.getApellidos() + " (" + alumnoMasJoven.getEdad() + " años)");
        txtAlumnosMayoresEdad.setText(String.valueOf(alumnosMayores));
        txtAlumnosMenoresEdad.setText(String.valueOf(alumnosMenores));
        if(!hayVacantes){
            txtNoHayVacantes.setText("No hay vacantes disponibles");
        }      
    }//GEN-LAST:event_btnEnviarActionPerformed
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblAlumnoMasJoven;
    private javax.swing.JLabel lblAlumnosMayoresEdad;
    private javax.swing.JLabel lblAlumnosMenoresEdad;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel txtAlumnoMasJoven;
    private javax.swing.JLabel txtAlumnosMayoresEdad;
    private javax.swing.JLabel txtAlumnosMenoresEdad;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private java.awt.Label txtNoHayVacantes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
